# frozen_string_literal: true
module MasterControl
  module Models
    class InsuranceCoverage < MasterControl::Models::Base
      attributes  \
        :id,
        :aasm_state,
        :carrier_id,
        :carrier_name,
        :cobra_inquiry_requested_at,
        :cobra_inquiry_requested_by_id,
        :cobra_follow_up_at,
        :cobra_follow_up_count,
        :cobra_insurance_coverage_id,
        :customer_id,
        :customer_app_state_id,
        :customer_provider_id,
        :effective_at,
        :group_number,
        :has_state_event,
        :has_valid_consent_on_file,
        :insurance_position,
        :insurance_sequence_id,
        :intake_id,
        :is_carve_out,
        :is_cobra,
        :is_valid,
        :is_verified,
        :last_validated_at,
        :last_verified_at,
        :member_id,
        :parent_insurance_coverage_id,
        :patient_id,
        :policy_holder_id,
        :policy_holder_first_name,
        :policy_holder_middle_name,
        :policy_holder_last_name,
        :policy_holder_date_of_birth,
        :primary_ended_at,
        :primary_started_at,
        :set_for_verification,
        :set_for_discovery,
        :state_event,
        :termed_at,
        :verified_by_id,
        :version,
        :is_sync_update,
        :created_at,
        :updated_at,
        :updated_by_id,
        :created_by_id,
        :active

      class << self
        # rubocop:disable Metrics/MethodLength
        def json_schema
          {
            type: 'object',
            properties: {
              canonical_klass: { type: 'string' },
              master_control_version: { type: 'string' },
              is_sync_update: { type: 'boolean' },
              version: { type: 'integer' },
              active: { type: 'boolean' },
              id: { type: 'string', pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              aasm_state: { type: 'string' },
              carrier_id: { type: 'string', pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              carrier_name: { type: ['string', 'null'] },
              cobra_inquiry_requested_at: { type: ['string', 'null'] },
              cobra_inquiry_requested_by_id: { type: ['string', 'null'], pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              cobra_follow_up_at: { type: ['string', 'null'] },
              cobra_follow_up_count: { type: ['integer', 'null'] },
              cobra_insurance_coverage_id: { type: ['string', 'null'], pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              customer_app_state_id: { type: ['string', 'null'], pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              customer_id: { type: 'string', pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              customer_provider_id: { type: 'string', pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              effective_at: { type: ['string', 'null'] },
              group_number: { type: ['string', 'null'] },
              has_valid_consent_on_file: { type: 'boolean' },
              has_state_event: { type: 'boolean' },
              insurance_position: { type: 'integer' },
              insurance_sequence_id: { type: ['string', 'null'], pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              intake_id: { type: ['string', 'null'], pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              is_carve_out: { type: 'boolean' },
              is_cobra: { type: 'boolean' },
              is_valid: { type: ['boolean', 'null'] },
              is_verified: { type: ['boolean', 'null'] },
              last_validated_at: { type: ['string', 'null'], format: 'date-time' },
              last_verified_at: { type: ['string', 'null'], format: 'date-time' },
              member_id: { type: 'string' },
              parent_insurance_coverage_id: { type: ['string', 'null'], pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              patient_id: { type: 'string', pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              policy_holder_id: { type: ['string', 'null'], pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              policy_holder_first_name: { type: ['string', 'null'] },
              policy_holder_middle_name: { type: ['string', 'null'] },
              policy_holder_last_name: { type: ['string', 'null'] },
              policy_holder_date_of_birth: { type: ['string', 'null'], format: 'date' },
              primary_ended_at: { type: ['string', 'null'] },
              primary_started_at: { type: ['string', 'null'] },
              set_for_verification: { type: 'boolean' },
              set_for_discovery: { type: 'boolean' },
              state_event: { type: ['string', 'null'] },
              termed_at: { type: ['string', 'null'] },
              verified_by_id: { type: ['string', 'null'], pattern: JSON_SCHEMA_PATTERNS[:uuid]  },
              created_at: { type: 'string', format: 'date-time' },
              updated_at: { type: 'string', format: 'date-time' },
              updated_by_id: { type: 'string', pattern: JSON_SCHEMA_PATTERNS[:uuid] },
              created_by_id: { type: 'string', pattern: JSON_SCHEMA_PATTERNS[:uuid] }
            },
            required: [
              :canonical_klass,
              :master_control_version,
              :is_sync_update,
              :version,
              :aasm_state,
              :carrier_id,
              :customer_id,
              :customer_provider_id,
              :group_number,
              :has_state_event,
              :has_valid_consent_on_file,
              :insurance_position,
              :is_carve_out,
              :is_cobra,
              :member_id,
              :patient_id,
              :set_for_verification,
              :set_for_discovery,
              :created_at,
              :updated_at,
              :updated_by_id,
              :created_by_id,
              :active
            ],
            additionalProperties: false
          }.to_json
        end
        # rubocop:enable Metrics/MethodLength
      end
    end
  end
end
