# frozen_string_literal: true
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'master_control', path: '../../'
gem 'rails', '~> 5.2.2'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'faker'
  gem 'rspec'
  gem 'rspec-rails'
end
